services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: bravetraveller

  backend:
    image: "candyypl/react-md-note-backend:1.0"
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      ALLOWED_ORIGIN: http://localhost:3000

  frontend:
    image: "candyypl/react-md-note-frontend:1.0"
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: http://localhost:8080
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
